<?php

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Component\Serialization\Json;
use Drupal\paragraphs\Entity\Paragraph;

/**
 * Implements hook_page_attachments().
 */
function nass_maps_page_attachments(array &$page){

  $path = \Drupal::requestStack()->getCurrentRequest()->getPathInfo();
  $path = trim($path, '/');
  $find = 'region-map';
  $pos = strpos($path, $find);

  if ($pos !== false) {

  } else {
    $page['#attached']['library'][] = 'nass_maps/nass_maps';
  }

}

/**
 * Implements hook_theme().
 */
function nass_maps_theme($existing, $type, $theme, $path) {
  return [
    'block__nass_us_map' => [],
  ];
}