<?php

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Component\Serialization\Json;
use Drupal\paragraphs\Entity\Paragraph;

/**
 * Implements hook_page_attachments().
 */
function nass_maps_page_attachments(array &$page){

  $page['#attached']['library'][] = 'nass_maps/nass_maps';

}

/**
 * Implements hook_theme().
 */
function nass_maps_theme($existing, $type, $theme, $path) {
  return [
    'block__nass_us_map' => [],
  ];
}