image:  node:11
options:
  max-time: 15

clone:
  depth: 20

pipelines:
  branches:
    kfoster-pipeline-testing:
      - step:
          name: Site Connectivity Test
          script:
            - curl http://nass-ingress.nass-www.10.0.12.94.nip.io/
    apache-qa-container:
      - step:
          name: Build and Publish WebMod Apache QA Container
          script:
            - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
            - docker build -f .docker/apache-qa/Dockerfile -t steampunkfoundry/apache-s3-push:latest ./.docker/apache
            - docker push steampunkfoundry/apache-s3-push:latest
          services:
            - docker
    mariadb-qa-container:
      - step:
          name: Build and Publish WebMod MariaDB QA Container
          script:
            - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
            - docker build -f .docker/mariadb-qa/Dockerfile -t steampunkfoundry/mariadb-s3-push:latest ./.docker/mariadb
            - docker push steampunkfoundry/mariadb-s3-push:latest
          services:
            - docker
    apache-staging-container:
      - step:
          name: Build and Publish WebMod Apache Staging Container
          script:
            - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
            - docker build -f .docker/apache-staging/Dockerfile -t steampunkfoundry/apache-s3-pull:latest ./.docker/apache
            - docker push steampunkfoundry/apache-s3-pull:latest
          services:
            - docker
    mariadb-staging-container:
      - step:
          name: Build and Publish WebMod MariaDB Staging Container
          script:
            - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
            - docker build -f .docker/mariadb-staging/Dockerfile -t steampunkfoundry/mariadb-s3-pull:latest ./.docker/mariadb
            - docker push steampunkfoundry/mariadb-s3-pull:latest
          services:
            - docker
