version: "3.9"
services:
  nass_website:
    container_name: "nass_website"
    mem_limit: "10G"
    image: kennethfoster/ewaps:php81
    working_dir: /var/application
    environment:
      DOCROOT: /var/application/web
      DATABASE_HOST: nass_mariadb
    volumes:
      - .:/var/application:delegated
      - ./local/files:/mnt/public-content:delegated
      - ./local/private:/mnt/private-content:delegated
    ports:
      - ${ENV_PORT}:80/tcp
    networks:
      - web
      - nass_internal

  nass_mariadb:
    image: mariadb:10.6
    container_name: "nass_mariadb"
    stop_grace_period: 30s
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      WAIT_TIMEOUT: 32800
      INTERACTIVE_TIMEOUT: 32800
    volumes:
      - ../nass-mysql:/var/lib/mysql:delegated
      - ../db-init:/docker-entrypoint-initdb.d:delegated
    ports:
      - 3306:3306/tcp
    networks:
      - nass_internal

networks:
  nass_internal:
    external: false
  web:
    external: false

