<?php

/**
 * @file
 * Install, update and uninstall functions for the Taxonomy Manager.
 */

/**
 * Implements hook_requirements().
 */
function taxonomy_manager_requirements($phase) {
  $requirements = [];

  // Report the version of Font Awesome.
  if ($phase == 'runtime') {
    $requirements['taxonomy_manager'] = [
      'title' => t('Taxonomy manager'),
    ];

    $library = \Drupal::service('library.discovery')->getLibraryByName('taxonomy_manager', 'jquery.fancytree');

    if (file_exists(DRUPAL_ROOT . '/' . $library['js'][0]['data'])) {
      $requirements['taxonomy_manager']['severity'] = REQUIREMENT_OK;
      $requirements['taxonomy_manager']['value'] = t('Fancytree library is found locally.');
    }
    else {
      $requirements['taxonomy_manager']['severity'] = REQUIREMENT_WARNING;
      $requirements['taxonomy_manager']['value'] = t('Fancytree library is not found locally.');
      $requirements['taxonomy_manager']['description'] = t('The fancytree library will be loaded via CDN, but consider adding it as a composer dependency.');
    }
  }

  return $requirements;
}

/**
 * Implements hook_install().
 */
function taxonomy_manager_install() {
  \Drupal::messenger()->addMessage(t("Taxonomy manager module has been enabled successfully."));
}

/**
 * Implements hook_uninstall().
 */
function taxonomy_manager_uninstall() {
  \Drupal::configFactory()->getEditable('taxonomy_manager.settings')->delete();
  \Drupal::messenger()->addMessage(t("Taxonomy manager module has been uninstalled successfully."));
}

/**
 * Issue #3164182: JQuery UI is being phased out from Drupal core.
 */
function taxonomy_manager_update_8200() {
  \Drupal::service('module_installer')->install([
    'jquery_ui',
  ]);
}
