oauth_login_oauth2.settings:
  type: mapping
  label: Settings
  mapping:
    miniorange_oauth_client_base_url :
      type: string
    miniorange_oauth_enable_login_with_oauth:
      type: boolean
    miniorange_oauth_send_with_header_oauth:
      type: boolean
    miniorange_oauth_send_with_body_oauth:
      type: boolean