<?php

use Drupal\Component\Serialization\Json;

function nass_cropland_page_attachments(array &$page){
  // Unconditionally attach an asset to the page.

  // $path = \Drupal::requestStack()->getCurrentRequest()->getPathInfo();
  // $path = trim($path, '/');

  $cropland_list = [];
  
  if (strpos($path,'cropland') !== false || strpos($path,'cropscape') !== false) {

  } else {
    
    //$page['#attached']['library'][] = 'nass_cropland/nass_cropland';

    $nids = \Drupal::entityQuery('node')->condition('type','cropland_data_layer_metadata')->execute();
    $nodes =  \Drupal\node\Entity\Node::loadMultiple($nids);

    foreach($nodes as $crop) {
      $title = $crop->getTitle();
      $paragraph = $crop->get('field_cropscape_and_cropland_dat');
      dump($paragraph);
      // if($crop->hasField('field_release_filename') && !$crop->get('field_release_filename')->isEmpty()) {
      //   $filename = $crop->field_release_filename->getString();
      // } else {
      //   $filename = '';
      // }
      //$url = $release->field_release_url->getValue();

      // $releasedate = $release->field_release_date_time->getValue();
      // $releasedate = strtotime($releasedate[0]['value']);
      // $releasedate = date('m/d/Y', $releasedate);

      $cropland_list[] = [
        'title' => $title
      ];
    }

    $cropland_list_json = Json::encode($cropland_list);
    dump($cropland_list_json);
  }
}