<?php

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Component\Serialization\Json;
use Drupal\paragraphs\Entity\Paragraph;

/**
 * Implements hook_page_attachments().
 */
function nass_regional_office_page_attachments(array &$page){
  // Unconditionally attach an asset to the page.
  $path = \Drupal::requestStack()->getCurrentRequest()->getPathInfo();
  $path = trim($path, '/');

  if(($path == 'about-nass/offices' || $path == 'about-nass/contact/offices')) { 
    $page['#attached']['library'][] = 'nass_regional_office/nass_regional_office';

    $node = \Drupal::routeMatch()->getParameter('node');
    $nid = $node->id();

    $paragraph_ids = $node->field_paragraph_content->getValue();

    $regional_offices = [];

    foreach($paragraph_ids as $pid){
      $region = Paragraph::load($pid['target_id']);
      if ($region->getType() === 'regional_office') {
        $region_color = $region->get('field_region_color')->getValue();
        $region_name = $region->get('field_regional_office_name')->getValue();
        $state_abrev_id = $region->get('field_state_list_selection')->getValue();

        $states = [];
        $states_abb = [];
        foreach($state_abrev_id as $state){
          $tid = $state['target_id'];
          $term_name = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->load($tid);
          $states[] = $term_name->get('field_state_abbreviation')->value;
          $states_abb[] = $states;
        }
        $regional_offices[] = [
          'region_name' => $region_name,
          'region_color' => $region_color,
          'state_abrev' => $states
        ];
      }
    }

    $regional_offices_json = Json::encode($regional_offices);
    $page['#attached']['drupalSettings']['regionalOffices'] = $regional_offices_json;

    //dsm($regional_offices_json);

  }

}

/**
 * Implements hook_theme().
 */
function nass_regional_office_theme($existing, $type, $theme, $path) {
  return [
    'block__nass_regional_office_map' => [],
  ];
}

/**
 * Implements hook_preprocess().
 */
function nass_regional_office_preprocess(&$variables){
  global $base_root, $base_path;
  $variables['nro_assets_path'] = $base_root . $base_path . drupal_get_path('module', 'nass_regional_office') . '/assets/';
}
