<?php

/**
 * Implements hook_preprocess_html().
 */
function nass_preprocess_html(&$variables) {
  // Get the current path
  $current_path = \Drupal::service('path.current')->getPath();
  $internal_path = \Drupal::service('path_alias.manager')->getAliasByPath($current_path);
  // Remove first slash in path
  $internal_path = ltrim($internal_path, "/");
  // Assign it to body class
  $variables['attributes']['class'][] = str_replace("/", "--", $internal_path);
}

/**
 * Implements hook_preprocess_page().
 */
function nass_preprocess_page(&$variables) {
  $site_config = \Drupal::config('system.site');
  $variables['site_name'] = $site_config->get('name');
  $variables['site_slogan'] = $site_config->get('slogan');

  // logo needs to be placed within specified folder
  $variables['logopath'] = \Drupal::service('file_url_generator')->transformRelative(\Drupal::service('file_url_generator')->generateAbsoluteString(theme_get_setting('logo.url')));

}

/**
 * Implements hook_preprocess_page_title().
 */
function nass_preprocess_page_title(&$variables) {
  $variables['url'] = $_SERVER['REQUEST_URI'];
  $variables['#cache']['contexts'][] = 'url.path';
}

/**
 * Implements hook_preprocess_block().
 */
function nass_preprocess_block(&$vars){
  $node = \Drupal::routeMatch()->getParameter('node');
  if ($node instanceof \Drupal\node\NodeInterface) {
    $vars["nid"] = $node->id();
    $vars["node_title"] = $node->getTitle();
  }
}

/**
 * Implements hook_preprocess().
 */
function nass_preprocess(&$variables, $hook){
  $variables['base_path'] = base_path();
}

/**
 * Implements hook_theme_suggestions_page_alter().
 */
function nass_theme_suggestions_page_alter(array &$suggestions, array $variables) {
  $is_front = $variables['is_front'] = \Drupal::service('path.matcher')->isFrontPage();
  if(!$is_front){
    if ($node = \Drupal::routeMatch()->getParameter('node')) {
      $content_type = $node->bundle();
      $suggestions[] = 'page__'.$content_type;
    }
  }

  // Response codes for Access Denied and Page Not Found.
  $system_codes = [403, 404];
  if (Drupal::request()->attributes->get('exception') &&
      $status_code = Drupal::request()->attributes->get('exception')->getStatusCode()) {
    // Add Basic Page suggestion if one of above response codes.
    if (in_array($status_code, $system_codes)) {
      $suggestions[] = 'page';
    }
  }

  if(!$is_front){
    if ($node = Drupal::routeMatch()->getParameter('node')) {
      $content_type = $node->bundle();
      $suggestions[] = 'page__'.$content_type;

        // for "page" content type only
        // if ($content_type == 'page'){

          if (in_array($content_type, array('landing_page','page'))) {

          $current_path = Drupal::service('path.current')->getPath();
          $alias = Drupal::service('path_alias.manager')->getAliasByPath($current_path);

          if ($alias != '')  {

            // break up the alias "/about/us"  => "", "about", "" ,"us"
            $parts = explode('/', $alias);

            // we only start suggestion with one "-" because first "/" will become extra "-"
            $suggestion = 'page__alias';

            foreach ($parts as $part) {
                // subsequent suggestions get appended
                $suggestion .= "_" . "$part";
            }

            // turn "-" in "_"
            $suggestion = str_replace("-", "_", $suggestion);
            $suggestions[] = $suggestion;

          }
        }

    }
  }

}

/**
 * Implements hook_theme_suggestions_paragraph_alter().
 */
function nass_theme_suggestions_paragraph_alter(&$suggestions, $variables) {
  $paragraph = $variables['elements']['#paragraph'];
  $parent = $paragraph->getParentEntity();
  if ($parent) {
    $suggestions[] = 'paragraph__' . $parent->bundle() . '__' .  $paragraph->bundle();
  }
}

/**
 * Implementation of hook_theme_suggestions_node_hook().
 */
function nass_theme_suggestions_node_alter(array &$suggestions, array $variables) {
  //dump($variables);
  $content_type = $variables['elements']['#node']->getType();
  //dump($content_type);
  if(isset($content_type)){
    $suggestions[] = 'node__' . $content_type;
  }
}

/**
 * Implementation of hook_theme_suggestions_block_hook().
 */
function nass_theme_suggestions_block_alter(&$suggestions, $variables) {
  if (isset($variables['elements']['content']['#block_content'])) {
    $bundle = $variables['elements']['content']['#block_content']->bundle();
    array_splice($suggestions, 1, 0, 'block__' . $bundle);
  }
}

/**
 * Implements hook_theme_suggestions_field_alter_hook()
 */
function nass_theme_suggestions_field_alter(&$suggestions, $variables) {
  // Prepare the array suggestion
  $suggestions = [];
  // Build a variable with field information

  $node = \Drupal::routeMatch()->getParameter('node');

  $element = $variables['element'];
  //dump($element);
  // sanitize #view_mode
  $sanitized_view_mode = strtr($element['#view_mode'], '.', '_');
  // Suggest template
  $suggestions[] = 'field__' . $element['#field_type'];
  $suggestions[] = 'field__' . $element['#field_name'];
  $suggestions[] = 'field__' . $element['#entity_type'] . '__' . $element['#bundle'];
  $suggestions[] = 'field__' . $element['#entity_type'] . '__' . $element['#field_name'];
  $suggestions[] = 'field__' . $element['#entity_type'] . '__' . $element['#field_name'] . '__' . $element['#bundle'];
  $suggestions[] = 'field__' . $element['#entity_type'] . '__' . $element['#field_name'] . '__' . $sanitized_view_mode;
  $suggestions[] = 'field__' . $element['#entity_type'] . '__' . $element['#field_name'] . '__' . $element['#bundle'] . '__' . $sanitized_view_mode;

  if(($element['#bundle'] == 'view') && (isset($element[0]['contents']))){
    $suggestions[] = 'field__' . $element['#entity_type'] . '__' . $element['#bundle'] . '__' . $element[0]['contents']['#name'] . '__' . $element[0]['contents']['#display_id'];
    $suggestions[] = $element['#entity_type'] . '__' . $element['#bundle'] . '__' . $element[0]['contents']['#name'] . '__' . $element[0]['contents']['#display_id'];
    $suggestions[] = 'views__' . $element['#bundle'] . '__' . $element[0]['contents']['#name'] . '__' . $element[0]['contents']['#display_id'];
    // dump($suggestions);
  }

  if(!empty($node)){
    $type = $node->getType();
    $suggestions[] = 'field__' . $element['#entity_type'] . '__' . $element['#field_name'] . '__' . $type;
    $suggestions[] = 'field__' . $element['#entity_type'] . '__' . $element['#field_name'] . '__' . $type . '__' . $element['#bundle'] . '__' . $sanitized_view_mode;
  }

}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 *
 * Add views unformatted template suggestions.
 *
 * @inheritdoc
 */
function nass_theme_suggestions_views_view_unformatted_alter(array &$suggestions, array $variables) {
  $suggestions[] = 'views_view_unformatted__' . $variables['view']->id();
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 *
 * Add views template suggestions.
 *
 * @inheritdoc
 */
function nass_theme_suggestions_views_view_alter(array &$suggestions, array $variables) {
  $suggestions[] = 'views_view__' . $variables['view']->id();
  //dump($variables);
}


/**
 * @param array $suggestions
 * @param array $variables
 * @param $hook
 */
function nass_theme_suggestions_views_view_field_alter(array &$suggestions, array &$variables, $hook){
  if ($variables['view']->id() && $variables['view']->current_display) {
      $suggestions[] = $hook . '__' . $variables['view']->id() . '__' . $variables['view']->current_display . '__' . $variables['field']->field;
  }
}

function nass_theme_suggestions_table_alter(array &$suggestions, array $variables){
  $class = $variables['attributes']['class'][0];
  $suggestions[] = "table__" . str_replace("-", "_", $class);
}
