<?php

use Drupal\views\ViewExecutable;

/**
 * Implements hook_preprocess().
 */
function nass_quick_stats_preprocess(&$variables) {
  $config = \Drupal::config('nass_quick_stats.adminsettings');

  global $base_root, $base_path;
  $variables['nqs_image_path'] = $base_root . $base_path . \Drupal::service('extension.path.resolver')->getPath('module', 'nass_quick_stats') . '/images';
  $textarea = $config->get('nass_quick_stats_textarea');
  $variables['nass_quick_stats_textarea'] = $textarea['value'];

  $disable = $config->get('nass_quick_stats_disable');
  $variables['nass_quick_stats_disable'] = $disable;

  $disable_msg = $config->get('nass_quick_stats_disabled_msg');
  $variables['nass_quick_stats_disabled_msg'] = $disable_msg;

  $variables['#attached']['drupalSettings']['quickStats']['url'] = $config->get('nass_quick_stats_url');

  $variables['#attached']['drupalSettings']['quickStats']['key'] = $config->get('nass_quick_stats_key');
  $variables['#attached']['drupalSettings']['quickStats']['params'] = '/quick-stats-sector';
  $variables['#attached']['drupalSettings']['quickStats']['groups'] = '/quick-stats-groups';
  $variables['#attached']['drupalSettings']['quickStats']['commodities'] = '/quick-stats-commodities';
  $variables['#attached']['drupalSettings']['quickStats']['results'] = '/quick-stats-results';
  $variables['#attached']['drupalSettings']['quickStats']['shortdesc'] = '/quick-stats-short-desc';
  $variables['#attached']['drupalSettings']['quickStats']['uuiddecode'] = '/quick-stats-uuid-decode';
}

/**
 * Implements hook_theme().
 */
function nass_quick_stats_theme($existing, $type, $theme, $path) {
  return [
    'page__quick_stats' => [
      'template' => 'page--quick-stats',
    ],
    'block__nass_quick_stats' => [],
  ];
}

/**
 * Implements hook_preprocess_block().
 */
function nass_quick_stats_preprocess_block(&$variables) {
  if ($variables['elements']['#id'] == 'nass_quick_stats') {
    $variables['#attached']['library'][] = 'nass_quick_stats/nass_quick_stats';
  }
}
