<?php

/**
 * Implements hook_page_attachments().
 */
function nass_quick_stats_page_attachments(array &$variables){
  // Unconditionally attach an asset to the page.
  $variables['#attached']['library'][] = 'nass_quick_stats/nass_quick_stats';
}

/**
 * Implements hook_preprocess().
 */
function nass_quick_stats_preprocess(&$variables) {
  $config = \Drupal::config('nass_quick_stats.adminsettings');

  $variables['#attached']['drupalSettings']['quickStats']['url'] = $config->get('nass_quick_stats_url');
  $variables['#attached']['drupalSettings']['quickStats']['params'] = '/quick-stats-sector';
  $variables['#attached']['drupalSettings']['quickStats']['groups'] = '/quick-stats-groups';
  $variables['#attached']['drupalSettings']['quickStats']['commodities'] = '/quick-stats-commodities';

}

/**
 * Implements hook_theme().
 */
function nass_quick_stats_theme($existing, $type, $theme, $path) {
  return [
    'page__quick_stats' => [
      'template' => 'page--quick-stats',
    ]
    // 'block__nass_quick_stats' => [],
    // 'block__nass_quick_stats_2' => [],
  ];
}