<?php

/**
 * Implements hook_page_attachments().
 */
function nass_release_page_attachments(array &$variables){
  // Unconditionally attach an asset to the page.
  $variables['#attached']['library'][] = 'nass_release/nass_release';
}

/**
 * Implements hook_theme().
 */
function nass_release_theme($existing, $type, $theme, $path) {
  return [
    'block__nass_release_todays_release' => [],
    'block__nass_release_whats_new' => [],
    'block__nass_release_year_list' => [],    
  ];
}

