<?php

use Drupal\Component\Serialization\Json;

/**
 * Implements hook_page_attachments().
 */
function nass_release_page_attachments(array &$page){
  // Unconditionally attach an asset to the page.
  $page['#attached']['library'][] = 'nass_release/nass_release';

  $nids = \Drupal::entityQuery('node')->condition('type','national_release')->execute();
  $nodes =  \Drupal\node\Entity\Node::loadMultiple($nids);

  $datetime = new DateTime("now", new DateTimeZone('America/New_York') );
  $now = $datetime->format('Y-m-d H:i:s');
  $today = $datetime->format('m/d/Y');

  $config = \Drupal::config('nass_release.adminsettings');
  $host_url_text = $config->get('nass_release_host_url');
  if (isset($host_url_text)) {
    $host_url = $host_url_text;
  } else {
    $host_url = 'https://release.nass.usda.gov/reports/';
  }
  $page['#attached']['drupalSettings']['nassRelease']['release_host'] = $host_url;

  $todays_releases = [];

  foreach($nodes as $release) {
    $title = $release->getTitle();
    $date = $release->field_release_date_time->getValue();
    $time = strtotime($date[0]['value']);
    $fulldatetime = date('Y-m-d H:i:s', $time);
    $time = date('g:i a', $time);
    if($release->hasField('field_release_filename') && !$release->get('field_release_filename')->isEmpty()) {
      $filename = $release->field_release_filename->getString();
    } else {
      $filename = '';
    }
    $url = $release->field_release_url->getValue();

    $releasedate = $release->field_release_date_time->getValue();
    $releasedate = strtotime($releasedate[0]['value']);
    $releasedate = date('m/d/Y', $releasedate);

    if($today == $releasedate){
      $todays_releases[] = [
        'title' => $title,
        'date' => $date,
        'time' => $time,
        'full_datetime' => $fulldatetime,
        'now' => $now,
        'host' => $host_url,
        'filename' => $filename,
        'url' => $url
      ];

    }
  }

  $todays_releases_json = Json::encode($todays_releases);
  $page['#attached']['drupalSettings']['nassRelease']['releaseData'] = $todays_releases;
  //dsm($todays_releases_json);

  $newdate = new DateTime('+1day');
  $tmw = $newdate->format('m/d/Y');
  $oneweek = new DateTime('+1 week');

  $upcoming_releases = [];

  $begin = new DateTime('+1day');
  $end = new DateTime('+7days');

  $interval = new DateInterval('P1D');
  $daterange = new DatePeriod($begin, $interval ,$end);

  foreach($nodes as $release) {
    $title = $release->getTitle();
    $date = $release->field_release_date_time->getValue();
    $time = strtotime($date[0]['value']);
    $dateformat = date('M d, Y', $time);
    $fulldatetime = date('Y-m-d H:i:s', $time);
    $time = date('g:i a', $time);
    $url = $release->field_release_url->getValue();

    $releasedate = $release->field_release_date_time->getValue();
    $releasedate = strtotime($releasedate[0]['value']);
    $releasedate = date('m/d/Y', $releasedate);

    foreach($daterange as $date){
      $date = $date->format('m/d/Y');
      if($date == $releasedate){
        $upcoming_releases[] = [
          'title' => $title,
          'date' => $date,
          'formatted_date' => $dateformat,
          'time' => $time,
          'full_datetime' => $fulldatetime,
          'url' => $url
        ];
        
      }
    }
  }
  
  $upcoming_releases = array_reverse($upcoming_releases);
  $upcoming_releases_json = Json::encode($upcoming_releases);
  $page['#attached']['drupalSettings']['nassRelease']['upcomingData'] = $upcoming_releases;
  //$page['#attached']['drupalSettings']['nassRelease']['currentTime'] = $now;

}

/**
 * Implements hook_preprocess().
 */
function nass_release_preprocess(&$variables) {
  $host_url;
  $config = \Drupal::config('nass_release.adminsettings');
  $variables['#attached']['drupalSettings']['nassRelease']['currentTime'] = '/nass-release-current-data';
  $textarea = $config->get('nass_release_textarea');
  if(isset($textarea)){
    $variables['#attached']['drupalSettings']['nassRelease']['no_release'] = $textarea['value'];
  } else {
    $variables['#attached']['drupalSettings']['nassRelease']['no_release'] = '';
  }

  $textarea_top = $config->get('nass_release_textarea_page_top');
  if(isset($textarea_top)) {
    $textarea_top_content = $textarea_top['value'];
  } else {
    $textarea_top_content = '';
  }
  $textarea_bottom = $config->get('nass_release_textarea_page_bottom');
  if(isset($textarea_bottom)) {
    $textarea_bottom_content = $textarea_bottom['value'];
  } else {
    $textarea_bottom_content = '';
  }
  $variables['todays_release_top_content'] = $textarea_top_content;
  $variables['todays_release_bottom_content'] = $textarea_bottom_content;

  $todays_release_disabled = $config->get('nass_release_disabled_message');
  $variables['todays_release_disabled'] = $todays_release_disabled;

  $disable_release = $config->get('nass_release_on_off_toggle');
  $variables['todays_release_toggle'] = $disable_release;

  $host_url_text = $config->get('nass_release_host_url');
  if (isset($host_url_text)) {
    $host_url = 'https://release.nass.usda.gov/reports/';
  } else {
    $host_url = $host_url_text;
  }
  $variables['#attached']['drupalSettings']['nassRelease']['release_host'] = $host_url;

}

/**
 * Implements hook_theme().
 */
function nass_release_theme($existing, $type, $theme, $path) {
  return [
    'block__nass_release_state_select' => [],
    'block__nass_release_todays_release' => [],
    'block__nass_release_whats_new' => [],
    'block__nass_release_year_list' => [],    
  ];
}

