<?php

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Component\Serialization\Json;
use Drupal\paragraphs\Entity\Paragraph;

/**
 * Implements hook_page_attachments().
 */
function nass_watershed_page_attachments(array &$page){
  // Unconditionally attach an asset to the page.
  $path = \Drupal::requestStack()->getCurrentRequest()->getPathInfo();
  $path = trim($path, '/');
  $find = 'census-by-watershed';
  $pos = strpos($path, $find);

  if ($pos !== false) {
    $page['#attached']['library'][] = 'nass_watershed/nass_watershed';
  }

}

/**
 * Implements hook_theme().
 */
function nass_watershed_theme($existing, $type, $theme, $path) {
  return [
    'block__nass_watershed' => [],
  ];
}
