<?php

/**
 * Implements hook_page_attachments().
 */
function nass_grid_overlay_page_attachments(array &$page){
    $page['#attached']['library'][] = 'nass_grid_overlay/nass_grid_overlay';
}

function nass_grid_overlay_page_bottom(array &$page_bottom) {
  $logged_in = \Drupal::currentUser()->isAuthenticated();
  if ($logged_in) {
    $page_bottom['nass_grid_overlay'] = [
      '#markup' => '
      <div id="grid-overlay-wrap">
        <div class="grid-container">
          <div class="grid-row grid-gap-lg">
            <div class="grid-col-1"><div class="col-inner">1/12</div></div>
            <div class="grid-col-1"><div class="col-inner">1/12</div></div>
            <div class="grid-col-1"><div class="col-inner">1/12</div></div>
            <div class="grid-col-1"><div class="col-inner">1/12</div></div>
            <div class="grid-col-1"><div class="col-inner">1/12</div></div>
            <div class="grid-col-1"><div class="col-inner">1/12</div></div>
            <div class="grid-col-1"><div class="col-inner">1/12</div></div>
            <div class="grid-col-1"><div class="col-inner">1/12</div></div>
            <div class="grid-col-1"><div class="col-inner">1/12</div></div>
            <div class="grid-col-1"><div class="col-inner">1/12</div></div>
            <div class="grid-col-1"><div class="col-inner">1/12</div></div>
            <div class="grid-col-1"><div class="col-inner">1/12</div></div>
          </div>
        </div>
      </div>'
    ];
  }
}