<?php

/**
 * @file
 * Install code for USWDS Paragraphs.
 */

use Drupal\Core\Config\FileStorage;
use Drupal\field\Entity\FieldStorageConfig;
use Drupal\field\Entity\FieldConfig;

/**
 * Helper function to add a field from our YAML config.
 *
 * @param string $bundle
 *   The name of the paragraph type.
 * @param string $field
 *   The name of the field.
 */
function _uswds_paragraphs_add_field($bundle, $field) {
  $module_handler = \Drupal::moduleHandler();
  $config_manager = \Drupal::service('config.manager');
  $entity_type_manager = \Drupal::entityTypeManager();

  $config_path = $module_handler->getModule('uswds_paragraphs')->getPath() . '/config/optional';
  $config_storage = new FileStorage($config_path);

  $config_name = "field.storage.paragraph.$bundle.$field";
  $config_record = $config_storage->read($config_name);
  if (!FieldStorageConfig::loadByName($config_record['entity_type'], $config_record['field_name'])) {
    $entity_type = $config_manager->getEntityTypeIdByName($config_name);
    $storage = $entity_type_manager->getStorage($entity_type);
    $entity = $storage->createFromStorageRecord($config_record);
    $entity->save();
  }

  $config_name = "field.field.paragraph.$bundle.$field";
  $config_record = $config_storage->read($config_name);
  if (!FieldConfig::loadByName($config_record['entity_type'], $config_record['bundle'], $config_record['field_name'])) {
    $entity_type = $config_manager->getEntityTypeIdByName($config_name);
    $storage = $entity_type_manager->getStorage($entity_type);
    $entity = $storage->createFromStorageRecord($config_record);
    $entity->save();
  }
}

/**
 * Helper function to delete a field.
 *
 * @param string $bundle
 *   The name of the paragraph type.
 * @param string $field
 *   The name of the field.
 */
function _uswds_paragraphs_delete_field($bundle, $field) {

  $entityFieldManager = Drupal::service('entity_field.manager');
  $fields = $entityFieldManager->getFieldDefinitions('paragraph', $bundle);
  if (isset($fields[$field])) {
    $fields[$field]->delete();
  }
}

/**
 * Add the new "Column to stretch" field on the "Row of columns" type.
 */
function uswds_paragraphs_update_8001() {
  _uswds_paragraphs_add_field('uswds_grid', 'field_uswds_grid_column_stretch');
}

/**
 * Delete the now-unused "Stretch to fill space" field on the "Column" type.
 */
function uswds_paragraphs_update_8002() {
  _uswds_paragraphs_delete_field('uswds_column', 'field_uswds_column_stretch');
}
