<?php

/**
 * @file
 * Functions to support theming in the Classy theme.
 *
 * No changes that impact functionality should be made to this file, as Classy
 * will be deprecated in Drupal 9. Changes should instead be made in the core
 * themes Bartik, Seven, Claro and/or Umami.
 */

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\classy\Hook\ClassyHooks;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_preprocess_links__media_library_menu().
 *
 * This targets the menu of available media types in the media library's modal
 * dialog.
 *
 * @todo Do this in the relevant template once
 *   https://www.drupal.org/project/drupal/issues/3088856 is resolved.
 */
#[LegacyHook]
function classy_preprocess_links__media_library_menu(array &$variables) {
  \Drupal::service(ClassyHooks::class)->preprocessLinksMediaLibraryMenu($variables);
}

/**
 * Implements hook_form_alter().
 */
#[LegacyHook]
function classy_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  \Drupal::service(ClassyHooks::class)->formAlter($form, $form_state, $form_id);
}

/**
 * Implements hook_preprocess_image_widget().
 */
#[LegacyHook]
function classy_preprocess_image_widget(array &$variables) {
  \Drupal::service(ClassyHooks::class)->preprocessImageWidget($variables);
}
