# ==================================================================================================================
# NOTE: This nginx config is only used for the local-only reverse proxy container used to allow authentication
#       to continue working on our local development machines.  Changes here WILL NOT make it to DEV or beyond...
# ==================================================================================================================

upstream web-nass_website {
    server nass_website:80;
}

server {
    listen 80;
    listen [::]:80;
    listen 8044;
    listen [::]:8044;
    server_name  localhost;

    access_log /var/log/nginx/access.log;
    error_log  /var/log/nginx/error.log debug;

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen      443 ssl;
    server_name localhost;

    ssl_certificate        /etc/nginx/localhost.crt;
    ssl_certificate_key    /etc/nginx/private/localhost.key;
    #ssl_client_certificate /etc/ssl/certs/ca.crt;
    ssl_verify_client      off;

    access_log /var/log/nginx/access.log;
    error_log  /var/log/nginx/error.log debug;

    location / {
        proxy_pass http://web-nass_website;

        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_connect_timeout       300;
        proxy_send_timeout          300;
        proxy_read_timeout          300;
        send_timeout                300;
    }
}
