on:
  push:
    branches: [ develop ]

name: Develop Latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Login to Azure Container Registry
        uses: docker/login-action@v4
        with:
          registry: ${{ secrets.NASS_CR_NAMESPACE }}
          username: ${{ secrets.NASS_CR_USER }}
          password: ${{ secrets.NASS_CR_PWD }}

      - name: build and push image
        run: |
          docker build -t nass_www_drupal:latest -f ./.docker/usda-nass-internal/Dockerfile .
          docker tag nass_www_drupal:latest ${{ secrets.NASS_CR_NAMESPACE }}/nass_www_drupal:latest
          docker push ${{ secrets.NASS_CR_NAMESPACE }}/nass_www_drupal:latest
          docker tag nass_www_drupal:latest ${{ secrets.NASS_CR_NAMESPACE }}/nass_www_drupal:dev
          docker push ${{ secrets.NASS_CR_NAMESPACE }}/nass_www_drupal:dev
